title: Avishek Roy
logo: Image/Photo for github page.png
description: Dad || Husband || Neuroscientist
59, Rue Kleber, Bordeaux Cedex- 33800, France
roy13avishek@gmail.com
show_downloads: false
theme: jekyll-theme-minimal
