title: Avishek Roy
logo: Image/Photo for github page.png
description: Dad || Husband || Neuroscientist Address- 59, Rue Kleber, Bordeaux Cedex- 33800, France.    email- roy13avishek@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
url: https://celefthe.com 
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: Avishek92 # your GitHub user name
# gitlab_username: # your GitLab user name
x_username: Avishek92 # your X handle
linkedin_username: avishek-roy-128727113 # your LinkedIn user name
scholar_userid: 176hxqAAAAAJ&hl # your Google Scholar ID
#semanticscholar_id: # your Semantic Scholar ID
orcid_id: 0000-0003-2633-487X # your ORCID ID
#zotero_username: # your zotero username
