# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Avishek # the website title (if blank, full name will be used instead)
first_name: Avishek
middle_name: 
last_name: Roy
email: roy13avishek@gmail.com
